name: "Crusty Javatrix"
description: "Just fooling around"
version: "0.0.24-DEV"
slug: "crusty-j"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: "world"
schema:
  username: str
