name: "Crusty Javatrix"
description: "Just fooling around"
version: "0.0.27-DEV"
slug: "crusty-j"
init: false
ports:
  9128/tcp: 9128
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: "world"
schema:
  username: str
